# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RedBasicaExport
                                 A QGIS plugin
 Export the sewer network designed using RedBasica to other formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-23
        copyright            : (C) 2025 by Leonardo Nazareth
        email                : leonazareth@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RedBasicaExport class from file RedBasicaExport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .redbasica_export import RedBasicaExport
    return RedBasicaExport(iface)
